### ISSUE TITLE
Error during compilation

### ISSUE THREAD

**Issue by amilanesi67** [DsChAeK/Picade#1]
I followed instructions but during Verify / Compile I had this errors:

In file included from C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino\USBAPI.h:38:0,

```
             from C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino\CDC.cpp:19:
```

C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino\CDC.cpp:56:71: error: 'USB_EP_SIZE' was not declared in this scope

  D_ENDPOINT(USB_ENDPOINT_OUT(CDC_ENDPOINT_OUT),USB_ENDPOINT_TYPE_BULK,USB_EP_SIZE,0),

```
                                                                   ^
```

C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino\USBCore.h:276:22: note: in definition of macro 'D_ENDPOINT'

  { 7, 5, _addr,_attr,_packetSize, _interval }

```
                  ^
```

C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino\CDC.cpp:57:71: error: 'USB_EP_SIZE' was not declared in this scope

  D_ENDPOINT(USB_ENDPOINT_IN (CDC_ENDPOINT_IN ),USB_ENDPOINT_TYPE_BULK,USB_EP_SIZE,0)

```
                                                                   ^
```

C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino\USBCore.h:276:22: note: in definition of macro 'D_ENDPOINT'

  { 7, 5, _addr,_attr,_packetSize, _interval }

```
                  ^
```

C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino\CDC.cpp:66:16: error: 'bool CDC_Setup' redeclared as different kind of symbol

 bool CDC_Setup(USBSetup& setup)

```
            ^
```

In file included from C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino\CDC.cpp:19:0:

C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino\USBAPI.h:267:6: note: previous declaration 'bool CDC_Setup(Setup&)'

 bool CDC_Setup(Setup& setup);

```
  ^
```

C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino\CDC.cpp:66:16: error: 'USBSetup' was not declared in this scope

 bool CDC_Setup(USBSetup& setup)

```
            ^
```

Uso la libreria EEPROM alla versione 2.0 nella cartella: C:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\EEPROM 
exit status 1
Errore durante la compilazione per la scheda Arduino Leonardo.

What happened?
Antonio

**Comment by DsChAeK** [comment]
Wrong arduino version? Be sure to use a fresh installed Arduino IDE v1.6.5 and have replaced the /USB_HID/ files.

**Comment by amilanesi67** [comment]
I used the last one, 1.6.12
It's wrong?

**Comment by amilanesi67** [comment]
Sorry, I copied the two files  found in your /USB_HID/  into Arduino install folder

**Comment by JOFAMILLY13** [comment]
Arduino : 1.6.12 (Windows 7), Carte : "Arduino Leonardo"

sketch\Picade.ino.cpp:1:21: fatal error: Arduino.h: No such file or directory

 #include <Arduino.h>

                     ^

compilation terminated.

exit status 1
Erreur de compilation pour la carte Arduino Leonardo

Ce rapport pourrait être plus détaillé avec
l'option "Afficher les résultats détaillés de la compilation"
activée dans Fichier -> Préférences.
voici mon message d'erreur je ne comprend pas help me please

**Comment by JOFAMILLY13** [comment]
Arduino : 1.6.12 (Windows 7), Carte : "Arduino Leonardo"

sketch\Picade.ino.cpp:1:21: fatal error: Arduino.h: No such file or directory

 #include <Arduino.h>

                     ^

compilation terminated.

exit status 1
Erreur de compilation pour la carte Arduino Leonardo

Ce rapport pourrait être plus détaillé avec
l'option "Afficher les résultats détaillés de la compilation"
activée dans Fichier -> Préférences.

**Comment by amilanesi67** [comment]
Avec Arduino IDE v1.6.5 tous va bien. Download ce version.

**Comment by DsChAeK** [comment]
As already mentioned, you have to use **v1.6.5**!

**Comment by JOFAMILLY13** [comment]
arduino 1.6.5 ok plus de probleme lors de la verification mais quand je televerse
la barre verte ce termine et puis rien pas ecris televersement termine ou autre et quand je demare la picade 
elle detecte toujour le joystick comme keyboard

**Comment by DsChAeK** [comment]
I know Arduino is not comfortable at all and therefore I wrote the **Compile/Flash** section and if you follow it step by step you should be successful if there are no USB connection problems.
